# Generated by Django 5.1.7 on 2025-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchased', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
    ]
